In [1]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity, manhattan_distances, cosine_distances, euclidean_distances   

In [3]:
#x = np.array([[0,0,60,11,21]])
#y = np.array([[40,11,4,11,14]])

def sklearn_cosine(x,y):
    return cosine_similarity(x, y)

def sklearn_mahnattan(x,y):
    return manhattan_distances(x, y)

def sklearn_euclidean(x,y):
    return euclidean_distances(x, y)

In [4]:
a = [0,5,0,0,0]
b = [0,4,0,0,0]

In [5]:
a = np.array(a)
b = np.array(b)

a = a.reshape(1,5)
b = b.reshape(1,5)

In [6]:
sklearn_cosine(a,b)

array([[1.]])

In [27]:
sklearn_mahnattan(a,b)

array([[10.]])

In [28]:
sklearn_euclidean(a,b)

array([[6.]])